### ISSUE TITLE
apex:tab doesn't work with visualstrap

### ISSUE THREAD

**Issue by Avinava** [Avinava/VisualStrap#14]

**Comment by Avinava** [comment]
Sorry for the late reply. Looks like this is issue with Jquery that visualstrap uses. You can try something like this

`
<apex:page >
    <c:importvisualstrap />
    <script>
        $j = jQuery.noConflict();
    </script>
    <c:visualstrapblock >
        <apex:form >
            <apex:tabPanel >
                <apex:tab label="TEST TAB 1">
                    Tab content 1
                </apex:tab>
                <apex:tab label="TEST TAB 2">
                    Tab content 2
                </apex:tab>
            </apex:tabPanel>
        </apex:form>
    </c:visualstrapblock>
</apex:page>
`

**Comment by ritzying** [comment]
Thank you!  Sorry for late reply... I didn't see this message
