### ISSUE TITLE
Problems with Tabs loading using Case Overview Example

### ISSUE THREAD

**Issue by ritzying** [Avinava/VisualStrap#21]
Hi there,

I am just learning some of these technologies, but just wondering if you can help me figure out 2 things.

#1 -- why the tabs aren't switching using your wonderful case overview example.
Here is my code:

<apex:page standardController="Deal__c" sidebar="false" docType="html-5.0" showHeader="false" >  
<apex:stylesheet value="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/0.16.1/css/semantic.css"/>
<apex:stylesheet value="/sCSS/25.0/sprites/1342034628000/Theme3/default/gc/versioning.css" />
<apex:stylesheet value="/sCSS/25.0/sprites/1342034628000/Theme3/default/gc/extended.css" />

<style>  
#container {
    margin: 45px;
    font-weight: 100;
}
</style>
<apex:include pageName="DealDetailView"/>
<div id="container">
<div class="ui one column grid">
    <div class="column">
      
    <div id="content" >
    <apex:tabPanel switchType="client" id="DealsTabPanel" tabClass="activeTab" inactiveTabClass="inactiveTab" >
      <apex:tab label="Details" name="cdetails" id="cdetails">
       <apex:detail relatedList="false" relatedListHover="false" title="true" inlineEdit="true"/> 
      </apex:tab>
    <apex:tab label="Tasks" name="ctasks" id="ctasks">
              <apex:ListViews type="Deal_Tasks__c" />  
     <apex:tab label="Deal Prep" name="DealPrep" id="tabDealPrep" >
        <apex:form >
        <apex:pageBlock >
        <apex:pageBlockButtons location="bottom">
                  <apex:commandButton action="{!cancel}" value="Cancel" 
                                      onclick="return confirmCancel()" immediate="true"/>
                  <apex:commandButton action="{!save}" value="Save"/>
      </apex:pageBlockButtons>
                <apex:pageBlockSection title="Deal Prep" columns="2">
                     <apex:inputField value="{!Deal__c.Location__c}"/>
                    <apex:inputField value="{!Deal__c.Office__c}"/>
                    <apex:inputField value="{!Deal__c.Other_Location__c}"/>
                      <apex:inputField value="{!Deal__c.Code__c}"/>
                    <apex:inputField value="{!Deal__c.Notes__c}"/>
                    <apex:inputField value="{!Deal__c.SentWhen__c}"/>
                      </apex:pageBlockSection>
                    </apex:pageBlock> 
                </apex:form>
        </apex:tab>
    </apex:tab>
                <apex:tab label="Emails" name="emails" id="emails" >
               <apex:ListViews type="Tasks__c" /> 
                </apex:tab>
 <apex:tab label="Open Activities" name="OpenActivities"
id="tabOpenAct">
<apex:relatedList subject="{!Deal__c}"
list="OpenActivities" />
</apex:tab>

<apex:tab label="History" name="ActivityHistory"
id="tabActHist" >
<apex:relatedList subject="{!Deal__c}"
list="ActivityHistories" pageSize="15" />
</apex:tab>
<apex:tab label="Attachments" name="CombinedAttachments"
id="tabCombinedAtt" >
<apex:relatedList subject="{!Deal__c}"
list="CombinedAttachments" pageSize="15" />
</apex:tab>
 <apex:tab label="Email Delivery" name="EmailDelivery" id="tabEmailDel" >
  </apex:tab>
    <apex:tab label="Feed" name="feed" id="tabfeed" >
               <div class="ui feed">
                <chatter:feed entityId="{!Deal__c.id}" feedItemType="TextPost"  showpublisher="True"></chatter:feed>
              </div>
              </apex:tab>
            </apex:tabPanel>
     </div>
</div>
</div>
</div>
</apex:page>

#2 
I am using the dashboard and it works great, except the number of items return in my query is limited to 3 even though I have set a limit in the controller to 10.  I also ran the query in workbench and it returned more than 3 records... but I can't get it to show more.

Thanks!

**Comment by Avinava** [comment]
Well can you try to attach the code again ?
Issue with records not been shown on the page seems to be related to query that you are doing. Visualstrap is a set of css and JS that doesnt modify actual data, but just lets you present them using bootstrap styles

**Comment by Avinava** [comment]
Sorry for the late reply. Looks like this is issue with Jquery that visualstrap uses. You can try something like this

```
<apex:page >
    <c:importvisualstrap />
    <script>
        $j = jQuery.noConflict();
    </script>
    <c:visualstrapblock >
        <apex:form >
            <apex:tabPanel >
                <apex:tab label="TEST TAB 1">
                    Tab content 1
                </apex:tab>
                <apex:tab label="TEST TAB 2">
                    Tab content 2
                </apex:tab>
            </apex:tabPanel>
        </apex:form>
    </c:visualstrapblock>
</apex:page>
```

**Comment by ritzying** [comment]
Hi there...

Ok... so here's the code for the query that is only returning 3 records total in each of the blocks on the dashboard.

public without sharing class VSDashBoard_Con2 { 
    public String deadline { get; set; }

   public List<Closing_Tasks__c> getTasks(){  
     return [SELECT Id,Reminder_Task__c,Due_Date__c, Closing__c FROM Closing_Tasks__c WHERE Due_Date__c >= TODAY AND Status__c != 'Completed' limit 10];  
   }  
   public List<Closing_Deadlines__c> getDeadlines(){  
     return [SELECT Closing__c,Due_Date_Selection__c,Due_Date__c,Status__c,Type__c FROM Closing_Deadlines__c WHERE Status__c = 'Binding' AND Due_Date_Selection__c >= TODAY ORDER BY Due_Date_Selection__c ASC NULLS LAST LIMIT 10];  
   }  
   public List<pba__Closing__c> getClosings(){  
     return [SELECT Address__c,ClosingDate__c, Name,Id FROM pba__Closing__c WHERE Status__c = 'Binding' ORDER BY ClosingDate__c ASC limit 10];  
   }  
   public List<Client__c> getBuyers(){  
     return [SELECT AddressFormula__c,Binding_Date__c,Closing_DateFormula__c,Id,Name__c,StatusFormula__c FROM Client__c WHERE StatusFormula__c = 'Binding' ORDER BY Name__c ASC NULLS FIRST limit 5 ];  
   }  
    public List<Client__c> getSellers(){  
     return [SELECT AddressFormula__c,Binding_Date__c,Closing_DateFormula__c,Id,StatusFormula__c FROM Client__c WHERE StatusFormula__c = 'Binding' ORDER BY Closing_DateFormula__c ASC NULLS FIRST limit 5 ];  
   } 
 }

I have adjusted the limits up and down and ran the query in Workbench and get more results.  Can you tell what I'm doing wrong?
