### ISSUE TITLE
Help with limits on query results in VSDashboard

### ISSUE THREAD

**Issue by ritzying** [Avinava/VisualStrap#22]
Could you please take a look and help me figure out why query only results in 3 records in the VSDashboard?  Query is fine in Workbench and returns lots of results and as you can see from the code, I have limits greater than 3.  Is there some limitation in Visualstrap?

Thank you for taking a look!

public without sharing class VSDashBoard_Con3 { 
    public String deadline { get; set; }

   public List<Tasks__c> getTasks(){  
     return [SELECT Address__c,Due_Date__c,Id,List__r.Id,Reminder_Task__c FROM List_Tasks__c WHERE Due_Date__c >= TODAY AND Status__c != 'Completed' ORDER BY Due_Date__c ASC NULLS LAST LIMIT 10];  
   }  
   public List<Appointment__c> getAppointments(){  
     return [SELECT Appointment_Date_Time__c,Id,Street_Address__c,Name__c FROM Appointment__c WHERE Appointment_Date_Time__c >= TODAY ORDER BY Appointment_Date_Time__c ASC NULLS FIRST LIMIT 10];  
   }  
   public List<Details__c> getDetails(){  
     return [SELECT Address__c,Id,Insurance__c,Street_Address__c FROM Details__c ORDER BY Date__c ASC NULLS LAST LIMIT 10];  
   }  
   public List<Appointment__c> getAgeds(){  
     return [SELECT Appointment_Date_Time__c,Id,Status__c,Name__c,Address__c FROM Appointment__c ORDER BY Name__c ASC NULLS LAST LIMIT 5 ];  
   }  
    public List<Sellers__c> getSellers(){  
     return [SELECT Address__c,Days_To_Expire__c,Id,List__r.Id,Contact__r.Id,Name__c,Status__c,Type__c FROM Sellers__c WHERE Type__c = 'Seller' AND Status__c = 'Active' ORDER BY Expiration__c ASC NULLS LAST LIMIT 5 ];  
   } 
 }

**Comment by thegogz** [comment]
Have you tried this with the apex:pageblocktable or other standard table element? 

Also could you provide your Visualforce page code? 

Remember to use ``` to post code here so its easier to read

**Comment by ritzying** [comment]
Hi... no I haven't tried using apex:pageblocktable or other standard table elements.

Here's VF page:

""<apex:page controller="VSDashBoard_Con3" sidebar="false" docType="html-5.0" showHeader="false">  
<c:lmenu ></c:lmenu>
   <vs:importvisualstrap />  
   <script>  
     function goToDetailPage(recId){  
       if(typeof sforce != 'undefined' && typeof sforce.one != 'undefined'){  
         sforce.one.navigateToSObject(recId);  
       }  
       else{  
         window.location.href = '/'+recId;  
       }  
       return false;  
     }  
   </script>  
   <vs:visualstrapblock style="padding: 0px 45px 0px 45px" >  
     <center>   
       <vs:pageheader title="list Dashboard" icon="calendar" subtitle="-- Hello {!$User.FirstName}"/>   
     </center>  
     <vs:row >  
       <vs:column type="col-md-4">  
         <vs:panel title="Tasks" type="primary">  
           <vs:well style="text-align:center;">  
              <vs:glyph icon="tasks" style="font-size:30px"/> &nbsp;<span style="font-size:44px">{!Tasks.size}</span>  
              <p class="text-muted">Pending Tasks</p>  
           </vs:well>  
      <apex:dataTable value="{!Tasks}" var="task" styleClass="table table-condensed table-hover table-bordered" rows="3">  
             <apex:column headerValue="Reminder/Task"> 
             <apex:outputLink onclick="return goToDetailPage('{!task.list__r.Id}')">{!task.Reminder_Task__c}
             </apex:outputLink> 
             </apex:column>  
             <apex:column value="{!task.Address__c}" headerValue="Address"/>  
             <apex:column value="{!task.Due_Date__c}" headerValue="Due Date"/>  
           </apex:dataTable> 
           <vs:alert rendered="{!Tasks.empty}" type="primary" style="text-align:center">  
             <vs:glyph icon="ok-sign"/> No tasks to display  
           </vs:alert>  
         </vs:panel>  
       </vs:column>  
 
 <vs:column type="col-md-4">  
         <vs:panel title="Appointments" type="danger">  
           <vs:well style="text-align:center;">  
              <vs:glyph icon="briefcase" style="font-size:30px"/>&nbsp;<span style="font-size:44px"></span>  
              <p class="text-muted">Already Scheduled</p>  
           </vs:well>  
           <apex:dataTable value="{!Appointments}" var="appointment" styleClass="table table-condensed table-hover table-bordered" rows="3">  
             <apex:column headerValue="Scheduled">
             <apex:outputField value="{!appointment.Appointment_Date_Time__c}"/> 
             </apex:column>  
             <apex:column headerValue="Address">   
              <apex:outputLink value="/{!appointment.id}">{!appointment.Street_Address__c}</apex:outputLink>
             </apex:column>  
             <apex:column value="{!appointment.Name__c}" headerValue="Seller">   </apex:column>  
             
           </apex:dataTable>  
           <vs:alert rendered="{!Appointments.empty}" type="danger" style="text-align:center">  
             <vs:glyph icon="exclamation-sign"/> No appointments to display  
           </vs:alert>  
         </vs:panel>  
       </vs:column>  
 
  <vs:column type="col-md-4">  
         <vs:panel title="Waiting" type="success">  
           <vs:well style="text-align:center;">  
              <vs:glyph icon="calendar" style="font-size:30px"/>&nbsp;<span style="font-size:44px">{!lists.size}</span>  
              <p class="text-muted">list Status</p>  
           </vs:well>  
        <apex:dataTable value="{!lists}" var="list" styleClass="table table-condensed table-hover table-bordered" rows="3">  
             <apex:column headerValue="Address">  
               <apex:outputLink onclick="return goToDetailPage('{!list.Id}')">{!list.Street_Address__c}</apex:outputLink>  
             </apex:column>  
             <apex:column value="{!list.Insurance__c}" headerValue="Inspection"/>      
           </apex:dataTable>  
           <vs:alert rendered="{!lists.empty}" type="success" style="text-align:center">  
             <vs:glyph icon="exclamation-sign"/> No lists to display  
           </vs:alert>  
         </vs:panel>  
       </vs:column>        
    </vs:row>
    
    <vs:row >  
    <vs:column type="col-md-6">  
         <vs:panel title="Potentials" type="primary">  
        <apex:dataTable value="{!Expireds}" var="expired" styleClass="table table-condensed table-hover table-bordered" rows="3">  
             <apex:column value="{!expired.Name__c}" headerValue="Name">      
             </apex:column> 
             <apex:column headerValue="Address">   
              <apex:outputLink value="/{!expired.id}">{!expired.Address__c}</apex:outputLink>
             </apex:column> 
              <apex:column value="{!expired.Status__c}" headerValue="Status">      
             </apex:column>   
           </apex:dataTable> 
           <vs:alert rendered="{!Expireds.empty}" type="info" style="text-align:center">  
             <vs:glyph icon="exclamation-sign"/> No records to display  
           </vs:alert>  
         </vs:panel>  
       </vs:column>     
       
    <vs:column type="col-md-6">  
         <vs:panel title="Actives" type="primary">  
          <apex:dataTable value="{!Sellers}" var="seller" styleClass="table table-condensed table-hover table-bordered" rows="3">  
             <apex:column headerValue="Name">  
             <apex:outputLink onclick="return goToDetailPage('{!seller.Id}')">{!seller.Name__c}</apex:outputLink>  
             </apex:column> 
             <apex:column headerValue="Address"> 
              <apex:outputLink onclick="return goToDetailPage('{!seller.List__r.Id}')">{!seller.Address__c}</apex:outputLink>
             </apex:column>  
             <apex:column value="{!seller.Expiration__c}" headerValue="Days to Expire"/> 
              
           </apex:dataTable>   
           <vs:alert rendered="{!Sellers.empty}" type="warning" style="text-align:center">  
             <vs:glyph icon="exclamation-sign"/> No records to display  
           </vs:alert>  
         </vs:panel>  
       </vs:column>     
   
  
     </vs:row>  
   </vs:visualstrapblock>  
 </apex:page>""

**Comment by ritzying** [comment]
Sorry ... not sure i made the right `` marks
