### ISSUE TITLE
glyphon not rendered

### ISSUE THREAD

**Issue by mark-d** [Avinava/VisualStrap#26]
Visualstrap 1.62 (spring 2015) managed packaged installed.
When try to preview a test page like 
```
<apex:page sidebar="false" docType="html-5.0">
 <vs:importvisualstrap />  
 <vs:visualstrapblock >  
    <vs:glyph icon="bookmark" />
 </vs:visualstrapblock>
</apex:page>
```
the glyph is not rendered.
This is caused by a by the following:

*Redirect at origin 'https: / / vs.na34.visual.force.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https: / / c.na34.visual.force.com' is therefore not allowed access.*

**Comment by Avinava** [comment]
closed with #27
