### ISSUE TITLE
Custom Components between vs: tags break the page

### ISSUE THREAD

**Issue by AndyRouse42** [Avinava/VisualStrap#31]
If a custom Visualforce component is placed between vs: tags, the page cannot load and produces the error "Unknown component c:Component_Name_Here". The exception appears to be <vs:visualstrapblock>, but all other components I've tested with seem to cause failure.

e.g.

```
<apex:page showHeader="false" docType="html-5.0" title="Visualstrap test">
	<vs:importvisualstrap />
	<vs:visualstrapblock >
		<vs:row >
			<c:ExampleComponent/>
		</vs:row>
	</vs:visualstrapblock>
</apex:page>
```

In this example, the custom component tag simply contains an image, but I've also tested with an empty component

**Comment by Avinava** [comment]
I think logged a issue with salesforce, basically the page is not able to resolve the namespaces. When you use non-namespaced component inside a managed component.

So if you use the unamanged version of visualstrap , it will work fine.

**Comment by AndyRouse42** [comment]
Ah, that's great! Thanks for letting me know.
